### ISSUE TITLE
xonsh 0.13 issue: module 'xonsh.jobs' has no attribute 'tasks'

### ISSUE THREAD

**Issue by AngellusMortis** [dyuri/xontrib-powerline-binding#7]
I am getting the following error in version 0.13.1 of `xonsh`:

```python
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/xonsh/events.py", line 182, in fire
    rv = handler(**kwargs)
  File "/usr/lib/python3.10/site-packages/xontrib/powerline_binding.xsh", line 29, in update_args
    powerline_args["jobnum"] = len(jobs.tasks)
AttributeError: module 'xonsh.jobs' has no attribute 'tasks'
```

Downgrading to 0.12.6 fixes it.

**Comment by dyuri** [comment]
New version (0.3.2) released with the fix, please check!

**Comment by AngellusMortis** [comment]
Looks good!
